import { useCallback, useEffect, useState } from "react"
import { useDispatch, useSelector } from "react-redux"
import { AppDispatch, AppState } from "state"

import { setFilter } from "state/pools/actions"

import { BigNumber } from "@ethersproject/bignumber"
import { IPool } from "constants/interfaces"
import { addPools } from "state/pools/actions"
import { getRandomPnl } from "utils"
import axios from "axios"

import defaultAvatar from "assets/icons/default-avatar.svg"

const responseToState = (data) => {
  return {
    firstName: data.CreatorAdr,
    lastName: "",
    avatar: defaultAvatar,

    ownerAddress: data.CreatorAdr,
    poolAddress: data.PoolAdr,
    baseAddress: data.BasicTokenAdr,

    symbol: data.Symbol,
    price: BigNumber.from((Math.random() * 100).toFixed(0)).toString(),
    priceUsd: Number((Math.random() * 100).toFixed(0)),

    copiers: Number((Math.random() * 100).toFixed(0)),
    rank: Number((Math.random() * 10).toFixed(1)),
    commision: Number((Math.random() * 100).toFixed(0)),
    personalFunds: BigNumber.from(0).toString(),
    personalFundsPercent: Number((Math.random() * 100).toFixed(0)),
    invested: BigNumber.from(0).toString(),
    profitFactor: Number((Math.random() * 100).toFixed(1)),
    trades: BigNumber.from(0).toString(),
    maxLoss: -Number((Math.random() * 100).toFixed(2)),

    avg: {
      dailyLpProfit: Number((Math.random() * 10).toFixed(0)),
      orderSize: Number((Math.random() * 10).toFixed(0)),
      timePosition: (Math.random() * 10).toFixed(2),
      tradesPerDay: Number((Math.random() * 100).toFixed(0)),
    },
    pnl: {
      total: 0,
      lpBasic: BigNumber.from(0).toString(),
      lpBasicPercent: 100,
      lpUsd: BigNumber.from(3700).toString(),
      lpUsdPercent: 102,
      monthly: [
        0,
        0,
        0,
        0,
        Number(getRandomPnl().toFixed(2)),
        Number(getRandomPnl().toFixed(2)),
        Number(getRandomPnl().toFixed(2)),
        Number(getRandomPnl().toFixed(2)),
        Number(getRandomPnl().toFixed(2)),
        Number(getRandomPnl().toFixed(2)),
        Number(getRandomPnl().toFixed(2)),
        Number(getRandomPnl().toFixed(2)),
      ],
      detailed: [
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: -Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: -Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: -Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: -Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: -Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: -Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: -Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: -Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: -Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: -Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: -Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: -Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: -Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: -Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: -Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: -Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: -Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: -Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: -Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: -Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: -Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: -Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: -Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: -Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
        {
          timestamp: new Date().toISOString(),
          lpBasic: BigNumber.from(0).toString(),
          lpBasicPercent: Number(getRandomPnl().toFixed(2)),
          lpUsd: BigNumber.from(3700).toString(),
          lpUsdPercent: 102,
        },
      ],
    },
    sortino: {
      base: 3.2,
      btc: 7.5,
    },
    supply: {
      circulating: BigNumber.from(0).toString(),
      total: BigNumber.from(0).toString(),
    },
  }
}

export function usePools(): [IPool[], boolean, boolean] {
  const dispatch = useDispatch<AppDispatch>()
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(false)

  const init = useCallback(
    (v: IPool[]) => {
      dispatch(addPools(v))
      setLoading(false)
      // setError(true)
    },
    [dispatch]
  )

  useEffect(() => {
    const getPools = async () => {
      const {
        data: { data },
      } = await axios.get(`${process.env.REACT_APP_STATS_API_URL}/pools/`)

      const pools = data.map(responseToState)
      setTimeout(() => init(pools), 1000)
    }
    getPools()
  }, [])

  const pools = useSelector<AppState, AppState["pools"]["list"]>((state) => {
    return state.pools.list
  })

  return [pools, loading, error]
}

export function usePoolsFilters(): [
  AppState["pools"]["filters"],
  (name: string, value: string) => void
] {
  const filters = useSelector((state: AppState) => state.pools.filters)

  const dispatch = useDispatch<AppDispatch>()
  const handleChange = (name, value) => dispatch(setFilter({ name, value }))

  return [filters, handleChange]
}

export function useSelectPoolByAddress(address: string): IPool | null {
  const pools = useSelector<AppState, AppState["pools"]["list"]>((state) => {
    return state.pools.list
  })

  const pool = pools.filter((pool) => pool.poolAddress === address)

  if (pool.length) {
    return pool[0]
  }

  return null
}

export function useSelectPools(): IPool[] {
  const pools = useSelector<AppState, AppState["pools"]["list"]>((state) => {
    return state.pools.list
  })

  return pools
}
